#!/bin/bash
# Based on article by Kevin Gamboa:
# https://medium.com/@kevin.gamboa/how-to-configure-a-pre-commit-for-a-flutter-application-29dfbb853366

printf "\e[33;1m%s\e[0m\n" 'Pre-Commit'

# Undo the stash of the files
pop_stash_files () {
    if [ -n "$hasChanges" ]; then
        printf "\e[33;1m%s\e[0m\n" '=== Applying git stash changes ==='
        git stash pop
    fi
}

# Stash unstaged files
hasChanges=$(git diff)
if [ -n "$hasChanges" ]; then
    printf "\e[33;1m%s\e[0m\n" 'Stashing unstaged changes'
    git stash push --keep-index
fi

# Flutter formatter
printf "\e[33;1m%s\e[0m\n" '=== Running Flutter Formatter ==='
flutter format .

hasNewFilesFormatted=$(git diff)
if [ -n "$hasNewFilesFormatted" ]; then
    git add .
    printf "\e[33;1m%s\e[0m\n" 'Formmated files added to git stage'
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running Flutter Formatter'
printf '%s\n' "${avar}"

# Flutter Analyzer
printf "\e[33;1m%s\e[0m\n" '=== Running Flutter analyzer ==='
flutter analyze
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" '=== Flutter analyzer error ==='
  pop_stash_files
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running Flutter analyzer'
printf '%s\n' "${avar}"

# Off emulator unit tests
printf "\e[33;1m%s\e[0m\n" '=== Running Off Emulator Unit Tests ==='
if [ -z "${INFURA_TOKEN}" ]; then
  echo "Missing INFURA_TOKEN environment variable"
  exit 1
fi

flutter test --dart-define=INFURA_TOKEN="${INFURA_TOKEN}" --dart-define=BSCSCAN_TOKEN="${BSCSCAN_TOKEN}" --dart-define=ETHERSCAN_TOKEN="${ETHERSCAN_TOKEN}" --dart-define=POLYGONSCAN_TOKEN_1="${POLYGONSCAN_TOKEN_1}" --dart-define=POLYGONSCAN_TOKEN_2="${POLYGONSCAN_TOKEN_2}" --dart-define=SNOWTRACE_TOKEN="${SNOWTRACE_TOKEN}"
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" '=== Off Emulator Unit Tests error ==='
  pop_stash_files
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running Off Emulator Unit Tests'
printf '%s\n' "${avar}"

# On emulator unit tests
printf "\e[33;1m%s\e[0m\n" '=== Running On Emulator Unit Tests ==='
flutter test integration_test
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" '=== On Emulator Unit Tests error ==='
  pop_stash_files
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running On Emulator Unit Tests'
printf '%s\n' "${avar}"

pop_stash_files
