name: Unit tests - off emulator
env:
  FLUTTER_VERSION: '3.0.4'

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install app dependencies
        run: flutter pub get
      - name: Analyze files
        run: flutter analyze
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Run unit tests directly with flutter test
        run: flutter test test --dart-define=INFURA_TOKEN=${{ secrets.INFURA_TOKEN }} --dart-define=BSCSCAN_TOKEN=${{ secrets.BSCSCAN_TOKEN }} --dart-define=ETHERSCAN_TOKEN=${{ secrets.ETHERSCAN_TOKEN }} --dart-define=POLYGONSCAN_TOKEN_1=${{ secrets.POLYGONSCAN_TOKEN_1 }} --dart-define=POLYGONSCAN_TOKEN_2=${{ secrets.POLYGONSCAN_TOKEN_2 }} --dart-define=SNOWTRACE_TOKEN=${{ secrets.SNOWTRACE_TOKEN }} --coverage

      - name: Upload unit tests coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
